export const COMPOSER_DATA = [


    { id: 1,
      firstName: "Wolfgang Amadeus",
      lastName: "Mozart",
      birthYear: 1756,
      deathYear: 1791,
      birthPlace: "Salzburg, Austria",
      image: "/assets/images/mozart.jpg",
      operas: []
    },
    { id: 2,
      firstName: "Richard",
      lastName: "Wagner",
      birthYear: 1813,
      deathYear: 1886,
      birthPlace: "Leipzig, Germany",
      image: "/assets/images/wagner.jpg",
      operas: []
    },
    { id: 3,
      firstName: "Giuseppe",
      lastName: "Verdi",
      birthYear: 1813,
      deathYear: 1901,
      birthPlace: "Le Roncole, Italy",
      image: "/assets/images/verdi.jpg",
      operas: []
    },
    { id: 4,
      firstName: "Giacomo",
      lastName: "Puccini",
      birthYear: 1856,
      deathYear: 1924,
      birthPlace: "Lucca, Italy",
      image: "/assets/images/puccini.jpg",
      operas: []
    },
    { id: 5, firstName: "Benjamin",
      lastName: "Britten",
      birthYear: 1913,
      deathYear: 1976,
      birthPlace: "Lowestoft, Great Britain",
      image: "/assets/images/britten.jpg",
      operas: []
    },
    { id: 6,
      firstName: "Richard",
      lastName: "Strauss",
      birthYear: 1864,
      deathYear: 1949,
      birthPlace: "München, Germany",
      image: "/assets/images/strauss.jpg",
      operas: []
    },
    { id: 7,
      firstName: "Sergei",
      lastName: "Prokofiev",
      birthYear: 1891,
      deathYear: 1953,
      birthPlace: "Sontsivka, Ukraine",
      image: "/assets/images/prokofiev.jpg",
      operas: []
    }
]
