export const COMPOSER_DATA = [


    { id: 1,
      firstName: "Wolfgang Amadeus",
      lastName: "Mozart",
      birthYear: 1756,
      deathYear: 1791,
      birthPlace: "Austria" },
    { id: 2,
      firstName: "Richard",
      lastName: "Wagner",
      birthYear: 1813,
      deathYear: 1886,
      birthPlace: "Germany" },
    { id: 3,
      firstName: "Giuseppe",
      lastName: "Verdi",
      birthYear: 1813,
      deathYear: 1901,
      birthPlace: "Le Roncole, Italy",
      image: "/assets/images/verdi.jpg",
      operas: []
    },
    { id: 4,
      firstName: "Giacomo",
      lastName: "Puccini",
      birthYear: 1856,
      deathYear: 1924,
      birthPlace: "Italy" },
    { id: 5, firstName: "Benjamin",
      lastName: "Britten",
      birthYear: 1913,
      deathYear: 1976,
      birthPlace: "Great Britain" },
    { id: 6,
      firstName: "Richard",
      lastName: "Strauss",
      birthYear: 1864,
      deathYear: 1949,
      birthPlace: "Germany" },
    { id: 7,
      firstName: "Sergei",
      lastName: "Prokofiev",
      birthYear: 1891,
      deathYear: 1953,
      birthPlace: "Russia" }



]
